build:
  environment:
    php: 7.3.25

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

filter:
  paths:
    - src/

  excluded_paths:
    - tests/
    - bin/
